"""
HLA Agent — Evaluation Report Generator
Produces a professional Markdown report with ranked tables,
winner analysis, and per-metric explanations.
"""

from datetime import datetime


def generate_report(ranked_candidates: list, requirements: dict,
                    run_id: str = "") -> str:
    """
    Generate a full Markdown evaluation report.

    Args:
        ranked_candidates: Sorted list from rank_candidates()
        requirements: Original requirements dict
        run_id: Optional run identifier

    Returns:
        Complete Markdown report string
    """
    project = requirements.get("project", "Unknown Project")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append(f"# HLA Agent — Architecture Evaluation Report")
    lines.append(f"")
    lines.append(f"**Project:** {project}  ")
    lines.append(f"**Generated:** {timestamp}  ")
    if run_id:
        lines.append(f"**Run ID:** {run_id}  ")
    lines.append(f"**Candidates Evaluated:** {len(ranked_candidates)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # === Ranking Table ===
    lines.append("## 📊 Candidate Rankings")
    lines.append("")
    lines.append("| Rank | Model | Style | RCR | NAS | SMI | LSCS | SCI | **CAS** | Verdict |")
    lines.append("|------|-------|-------|-----|-----|-----|------|-----|---------|---------|")

    for c in ranked_candidates:
        s = c.get("scores", {})
        verdict_icon = {"Accepted": "✅", "Marginal": "⚠️", "Poor": "❌"}.get(
            s.get("verdict", ""), "❓"
        )
        lines.append(
            f"| {c['rank']} | {c['model']} | {c.get('architecture', {}).get('architecture_style', 'N/A')} "
            f"| {s.get('RCR', 0):.2f} | {s.get('NAS', 0):.2f} | {s.get('SMI', 0):.2f} "
            f"| {s.get('LSCS', 0):.2f} | {s.get('SCI', 0):.2f} "
            f"| **{s.get('CAS', 0):.4f}** | {verdict_icon} {s.get('verdict', '')} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    # === Winner Analysis ===
    if ranked_candidates:
        winner = ranked_candidates[0]
        ws = winner.get("scores", {})
        wa = winner.get("architecture", {})

        lines.append("## 🏆 Winner Analysis")
        lines.append("")
        lines.append(f"- **Model:** {winner['model']}")
        lines.append(f"- **Architecture Style:** {wa.get('architecture_style', 'N/A')}")
        lines.append(f"- **CAS Score:** {ws.get('CAS', 0):.4f}")
        lines.append(f"- **Verdict:** {ws.get('verdict', 'N/A')}")
        lines.append(f"- **Components:** {len(wa.get('components', []))}")
        lines.append(f"- **Interactions:** {len(wa.get('interactions', []))}")
        lines.append(f"- **Layers:** {len(wa.get('layers', []))}")
        lines.append("")

        # Component list
        lines.append("### Components")
        lines.append("")
        lines.append("| Component | Layer | Responsibility |")
        lines.append("|-----------|-------|----------------|")
        for comp in wa.get("components", []):
            lines.append(
                f"| {comp.get('name', '')} | {comp.get('layer', '')} "
                f"| {comp.get('responsibility', '')} |"
            )
        lines.append("")

    # === Metric Details ===
    lines.append("---")
    lines.append("")
    lines.append("## 📈 Metric Definitions")
    lines.append("")
    lines.append("| Metric | Full Name | Weight | Threshold |")
    lines.append("|--------|-----------|--------|-----------|")
    lines.append("| RCR | Requirement Coverage Ratio | 25% | ≥ 0.80 |")
    lines.append("| NAS | NFR Alignment Score (Deterministic Rules Engine) | 25% | ≥ 0.75 |")
    lines.append("| SMI | Structural Modularity Index | 20% | ≥ 0.75 |")
    lines.append("| LSCS | Layer Separation Consistency Score | 15% | ≥ 0.90 |")
    lines.append("| SCI | Structural Clarity Index | 15% | ≥ 0.80 |")
    lines.append("")
    lines.append("**Phase 1 CAS** = 0.50×RCR + 0.50×NAS (tradeoff selection gate)")
    lines.append("")
    lines.append("**Phase 2 CAS** = 0.25×RCR + 0.25×NAS + 0.20×SMI + 0.15×LSCS + 0.15×SCI")
    lines.append("")
    lines.append("LSCS is style-aware for Layered, Event-Driven, Microkernel, Microservices, and Space-Based architectures.")
    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by HLA Agent v1.0*")

    return "\n".join(lines)
